# Gradle-Einstellungen
org.gradle.jvmargs=-Xmx3G

# Mod-Eigenschaften
mod_version = 1.0.0
maven_group = net.example.nametag
archives_base_name = nametag_toggle

# Minecraft & Fabric Versionen (1.26.3)
minecraft_version = 1.26.3
yarn_mappings = 1.26.3+build.1:v2
loader_version = 0.16.10

# Fabric API (0.161.0+26.3)
fabric_version = 0.161.0+26.3