# Gradle-Einstellungen
org.gradle.jvmargs=-Xmx3G

# Mod-Eigenschaften
mod_version = 1.0.0
maven_group = net.example.nametag
archives_base_name = nametag_toggle

# Minecraft & Fabric Versionen
minecraft_version = 1.21.4
yarn_mappings = 1.21.4+build.1:v2
loader_version = 0.16.10

# Fabric API
fabric_version = 0.115.0+1.21.4